### ISSUE TITLE
Client의 recv_startline 구현

### ISSUE THREAD

**Issue by cos18** [404-DriverNotFound/418-imateapot#3]
HTTP 헤더가 들어왔다고 가정해서 해더 파싱하기 (recv_startline)

**Comment by hyo-choi** [comment]
구현은 끝났는데 논의해서 적용해야 할 사항이 있어서 PR 보류중입니다...
 
### 논의할 부분
- 쿼리 스트링 처리
- StartLine, Http 클래스 구조
- Url, Path 클래스 존속 여부
